name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    name: Build
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Git LFS
        run: |
          git lfs update --force
          git lfs install
      - name: Set up elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
      - name: Build project
        run: ~/.elan/bin/lake build
      - name: Download model
        run: |
          export GIT_CLONE_PROTECTION_ACTIVE=false
          ~/.elan/bin/lake exe LeanCopilot/download
      - name: Build tests
        run: ~/.elan/bin/lake build LeanCopilotTests
